mode:  # Operation mode flags
    VARY_POINT: True  # Determines if we vary the prod point or set it to (0,0)
    NUM_EVENTS: 1  # Number of events to generate -- 0 runs events until interrupt.
    NUM_SAMPLES: 100  # Number of hard jet production processes to run in each event
    KEEP_EVENT: False  # Keep plasma data for future analysis
    KEEP_RECORD: False  # Save xarray parton record - includes trajectory & pT history
trento:
    NORM: 20  # Overall normalization factor for reduced thickness function (and thereby multiplicity)
    PROJ1: 'Pb'  # Collisions species 1
    PROJ2: 'Pb'  # Collisions species 2
    NUCLEON_WIDTH: 0.92  # [fm] Gaussian nucleon width in fm. Default 0.5 fm from DukeQCD BA
    CROSS_SECTION: 7.0  # [fm^2] Inelastic nucleon-nucleon cross section sigma_{NN} in fm^2 - Changes w/ beam energy
    BMIN: None  # [fm?] Minimum impact parameter. For no limits, set None.
    BMAX: None  # [fm?] Maximum impact parameter. For no limits, set None.
    P: 0  # Nuclear overlap power parameter (default 0)
    K: 0.19  # Gamma distribution shape parameter k for nucleon fluctuations
    V: 0.43  # [fm] Gaussian constituent width
    NC: 6  # Number of nucleon constituents
    DMIN: 0.81  # [fm] Minimum nucleon distance
transport:  # Parameters for the hybrid transport medium model - freestreaming, hydro, frzout, & UrQMD
    TAU_FS: 0.37  # [fm] freestreaming time. Default 0.5 fm.
    GRID_STEP: 0.1  # [fm] Hydro / Trento grid step in fm. Default 0.15*NUCLEON_WIDTH from DukeQCD BA
    TIME_STEP: 0.05  # [fm] Hydro / Trento time step in fm. Default 0.25*GRID_STEP fm from DukeQCD BA
    GRID_MAX_TARGET: 15  # [fm] Maximum hydro grid width.
    T_SWITCH: 0.151  # [GeV] Minimum temperature in GeV of all cells at which to cut off hydro evolution.
    ETAS_MIN: 0.11  # eta/s at T0
    ETAS_SLOPE: 1.6  # [GeV^-1] slope of (eta/s)(T) above T0
    ETAS_CURV: -0.29  # curvature of (eta/s)(T) above T0 (see osu-hydro readme)
    ZETAS_MAX: 0.032  # maximum value of zeta/s (at T0)
    ZETAS_WIDTH: 0.024  # [GeV] width of (zeta/s)(T)
    ZETAS_T0: 0.175  # [GeV] peak location of Cauchy (zeta/s)(T)
jet:  # Parameters for the jet production processes to be run
    PTHATMIN: 1  # [GeV] Minimum pTHat for jet production hard scatterings ~ min initial pT of jets
    PTHATMAX: 100  # [GeV] Maximum pTHat for jet production hard scatterings ~ max initial pT of jets
    DTAU: 0.1  # [fm] Timestep used for parton propagation -- plasma properties assumed constant over dtau
    T_HRG: 0.155  # [GeV] Temperature in GeV at which to consider the medium hadronized - cuts off el & drift
    T_UNHYDRO: 0.150  # [GeV] Temperature in GeV at which to consider the medium unhydrodynamic
    K_F_DRIFT: 1  # Scale factor for flow drift effect - default realistic estimate is 1
    K_FG_DRIFT: 1  # Scale factor for flow-gradient drift effects - default realistic estimate is 1
global_constants:  # Physical constants to be set by the user.
    # Coupling is set by case selection in ebe scripts. Uses G_RAD by default.
    G_RAD: 1.9  # Coupling constant for IN-MEDIUM strong interaction w/ radiative energy loss
    G_COL: 1.6  # Coupling constant for IN-MEDIUM strong interaction w/ radiative **&** collisional energy loss
    ROOT_S: 5020  # [GeV] sqrt(s) in GeV of collision system - also change Trento cross-section!
